import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={cn("bg-slate-800 text-slate-900 antialiased light", inter.className)}>
      <body className="min-h-screen h-screen  bg-zinc-900  antialiased">{children}</body>
    </html>
  );
}
